#!/usr/bin/env node
/**
 * Audit the copied TECM8 monitor with AZM register contracts enabled.
 *
 * This is intentionally separate from the production ROM build. The copied
 * MON3 source is legacy assembly and does not yet pass strict contracts.
 */

const { mkdirSync, writeFileSync } = require('node:fs');
const { dirname, relative, resolve } = require('node:path');

const TECM8_ROOT = resolve(__dirname, '..');
const AZM_ROOT = process.env.AZM_ROOT ? resolve(process.env.AZM_ROOT) : undefined;
const SOURCE_FILE = resolve(TECM8_ROOT, 'roms/tec1g/tecm8/monitor/monitor.asm');
const REPORT_PATH = resolve(TECM8_ROOT, 'docs/mon3/monitor-register-contract-audit.md');

type Diagnostic = {
  severity?: string;
  code?: string;
  sourceName?: string;
  line?: number;
  column?: number;
  message?: string;
};

type CompileResult = {
  diagnostics: Diagnostic[];
};

function rel(path: string | undefined): string {
  return path ? relative(TECM8_ROOT, path) : 'unknown';
}

function formatFileTable(diagnostics: Diagnostic[]): string {
  const counts = new Map<string, number>();
  for (const diagnostic of diagnostics) {
    const file = rel(diagnostic.sourceName);
    counts.set(file, (counts.get(file) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([file, count]) => `| ${file} | ${count} |`)
    .join('\n');
}

function formatDiagnostics(diagnostics: Diagnostic[]): string {
  return diagnostics
    .map((diagnostic) => {
      const file = rel(diagnostic.sourceName);
      const line = diagnostic.line ?? 0;
      const column = diagnostic.column ?? 0;
      const severity = diagnostic.severity ?? 'unknown';
      const code = diagnostic.code ?? 'unknown';
      const message = diagnostic.message ?? '';
      return `| ${file}:${line}:${column} | ${severity} | ${code} | ${message.replace(/\|/g, '\\|')} |`;
    })
    .join('\n');
}

function renderReport(diagnostics: Diagnostic[]): string {
  return `# Monitor Register Contract Audit

This report is generated by \`npm run mon3:contracts:audit\`. It assembles the
copied TecMate monitor source with AZM register contracts enabled in strict mode:

\`\`\`text
registerCare: strict
registerCareProfile: mon3
\`\`\`

The production monitor ROM build deliberately keeps register contracts off for
now because the copied MON3 source is legacy code and does not yet describe its
register/flag behavior in AZMDoc form.

## Summary

Strict contract diagnostics: \`${diagnostics.length}\`

| File | Diagnostics |
| --- | ---: |
${formatFileTable(diagnostics)}

## Interpretation

This is an audit baseline, not a release gate. The diagnostics mostly mean AZM
cannot prove that a value or flag used after a \`CALL\` survived that call. Some
will be real bugs or fragile assumptions; many will be missing or overly broad
contracts on legacy helper routines.

The priority should not be to fix all of this before moving TecMate forward.
The immediate priority is to keep contracts strict for new TecMate code, while
using this report to decide where legacy monitor sanitising is worth doing.

Lower-priority areas:

- PATA/FAT32 storage code, because the direction is to replace it with TEC-FS.
- GLCD terminal/library code, because the direction is to move GLCD services out
  of the fixed monitor and into a banked service boundary.
- RTC UI, because the useful RTC service entry points can stay while the UI is a
  later relocation candidate.

Higher-priority areas:

- Fixed ROM bank-switching and RST 10h services.
- Monitor command/menu code that remains in MON3Lite.
- Disassembler entry points if the disassembler stays resident.
- Small shared LCD/keypad/serial helpers that many retained monitor paths call.

## Recommended Plan

1. Keep production monitor builds contract-free until the legacy surface is
   intentionally sanitised.
2. Keep strict contracts enabled for new TecMate source, proofs, and small
   libraries.
3. Add or improve contracts only when touching retained monitor code.
4. Do not spend time annotating PATA/FAT32 or old GLCD implementation paths
   unless they unexpectedly remain resident.
5. Consider asking AZM for a quarantine mechanism: per-file or per-include
   contract suppression, so retained new code can stay strict while imported
   legacy monitor files remain audited but non-blocking.
6. Re-run this audit after major monitor reductions so the remaining diagnostic
   set reflects the code we actually intend to keep.

## Diagnostics

| Location | Severity | Code | Message |
| --- | --- | --- | --- |
${formatDiagnostics(diagnostics)}
`;
}

function unexpectedDiagnostics(diagnostics: Diagnostic[]): Diagnostic[] {
  return diagnostics.filter((diagnostic) => diagnostic.code !== 'AZMN_REGISTER_CONTRACTS');
}

async function main(): Promise<void> {
  const { compile, defaultFormatWriters } = AZM_ROOT
    ? await import(resolve(AZM_ROOT, 'dist/src/api-compile.js'))
    : await import('@jhlagado/azm/compile');

  const result = (await compile(
    SOURCE_FILE,
    {
      emitBin: true,
      outputType: 'bin',
      sourceRoot: TECM8_ROOT,
      registerCare: 'strict',
      registerCareProfile: 'mon3',
    },
    { formats: defaultFormatWriters }
  )) as CompileResult;

  const unexpected = unexpectedDiagnostics(result.diagnostics);
  if (unexpected.length > 0) {
    throw new Error(`Unexpected AZM diagnostics:\n${JSON.stringify(unexpected, null, 2)}`);
  }

  mkdirSync(dirname(REPORT_PATH), { recursive: true });
  writeFileSync(REPORT_PATH, renderReport(result.diagnostics));
  console.log(`Wrote ${REPORT_PATH}`);
  console.log(`Strict contract diagnostics: ${result.diagnostics.length}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
